server:
  port: 8080

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: MYHOUSE
    password: MYHOUSE

  jpa:
    hibernate:
      ddl-auto: validate   # 개발: update / 운영: validate 또는 none 권장
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.OracleDialect
    open-in-view: false  # 컨트롤러에서 지연로딩 터지는 문제 예방(서비스에서 해결하는 습관)

logging:
  level:
    org.springframework.transaction: TRACE
    org.springframework.transaction.interceptor: TRACE
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.SQL: DEBUG
    org.springframework.orm.jpa: DEBUG
    org.springframework.dao: DEBUG

