-- schema_oracle.sql
-- Oracle 기준 스키마(사용자) 및 테이블 생성 스크립트

--  테이블 생성 (IDENTITY 사용)
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE users (
      id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name VARCHAR2(255) NOT NULL,
      email VARCHAR2(255) NOT NULL UNIQUE,
      created_at TIMESTAMP DEFAULT SYSTIMESTAMP
    )
  ';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN
      NULL; -- ORA-00955: name is already used by an existing object
    ELSE
      RAISE;
    END IF;
END;
/

-- 5) 샘플 데이터
INSERT INTO users (name, email) VALUES ('John Doe', 'john@example.com');
INSERT INTO users (name, email) VALUES ('Jane Smith', 'jane@example.com');
INSERT INTO users (name, email) VALUES ('Bob Johnson', 'bob@example.com');

COMMIT;
